---
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    # FIXME
    # - idempotence
    - verify
    - lint

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: webmtogif_deploy_test
    image: docker.io/geerlingguy/docker-ubuntu2004-ansible
    # for simulate systemd
    # Also, do not install systemd>=248 in host system, it broke tests
    # https://github.com/moby/moby/issues/42275
    command: "/lib/systemd/systemd"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  sudo: true
verifier:
  name: testinfra

ansible:
  vault_password_file: .vault

# Temporary disable ansible-lint
lint: |
  set -e
  yamllint roles/
  flake8 roles/

